#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/PA5/PA5 
mpiexec -np 5 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
