#!/bin/bash
#PBS -l nodes=3:ppn=12
#PBS -l walltime=00:03:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/PA3
mpiexec -np 3 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
