#!/bin/bash
#PBS -l nodes=10:ppn=12
#PBS -l walltime=00:03:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/PA3
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
mpiexec -np 5 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
mpiexec -np 8 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
mpiexec -np 10 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.x
