#!/bin/bash
#PBS -l nodes=10:ppn=12
#PBS -l walltime=00:03:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe

cd ~/assignments/Parallel-Assigment/PA2/
mpiexec -np 10 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./PA2.x
