#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/final
mpiexec -bind-to none -np 6 --map-by core  --hostfile $PBS_NODEFILE ./*.cx

