#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:06:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/final
mpiexec -bind-to none -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./*.cx

