#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N first_run
#PBS -j oe
cd ~/assignments/Parallel-Assigment/final
export OMP_NUM_THREADS=1
mpiexec -np 6 --map-by ppr:1:node --bind-to none --hostfile $PBS_NODEFILE ./*.cx 
